### ISSUE TITLE
Cannot find package 'meow'

### ISSUE THREAD

**Issue by datn** [wmde/wikibase-seed-data#4]
This script seems to be failing when trying to use the "meow" package. In the package lock file I can see and download the module from the given path:

```
      "resolved": "https://registry.npmjs.org/meow/-/meow-9.0.0.tgz",
```
so I'm not sure why the dependency would fail.

```
> wikibase-seed-data@1.0.0 seed /home/node/app
> node index.js "-s" "./all-property-datatypes.js"

internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'meow' imported from /home/node/app/index.js
    at new NodeError (internal/errors.js:322:7)
    at packageResolve (internal/modules/esm/resolve.js:732:9)
    at moduleResolve (internal/modules/esm/resolve.js:773:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:887:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wikibase-seed-data@1.0.0 seed: `node index.js "-s" "./all-property-datatypes.js"`
npm ERR! Exit status 1

```

**Comment by tarrow** [comment]
I didn't check this out recently to try it but did you first run `npm install` ? This should probably be documented in the readme but often omitted due to the implicit knowledge of JS developers

**Comment by datn** [comment]
Thanks, I ran `npm install` which gave way to a new error message. Before I get deeper into this though -- should I expect the code in this repo to work with a wikibase.cloud instance?

**Comment by deer-wmde** [comment]
> should I expect the code in this repo to work with a wikibase.cloud instance?

I think the answer is: sadly no :(

I just took a brief look and tried to use this with my local instance of wikibase.cloud, while it looks like it could work, my guess is this script is expecting to make edits without logging in as a user, which per default isn't allowed on wikibase.cloud wikis

```
$ MW_SERVER=http://debugdebugdebug2.wbaas.localhost MW_SCRIPT_PATH=/w docker-compose run node npm run seed -- -s './all-property-datatypes.js'
Creating wikibase-seed-data_node_run ... done

> wikibase-seed-data@1.0.0 seed /home/node/app
> node index.js "-s" "./all-property-datatypes.js"

Server failed to create entity: You do not have the permissions needed to carry out this action.
You do not have the permissions needed to carry out this action.
Server failed to create entity: You do not have the permissions needed to carry out this action.
You do not have the permissions needed to carry out this action.
Server failed to create entity: You do not have the permissions needed to carry out this action.
You do not have the permissions needed to carry out this action.
Server failed to create entity: You do not have the permissions needed to carry out this action.
You do not have the permissions needed to carry out this action.
```
